xgboost:
  objective: multi:softmax
  num_class: 3
  learning_rate: 0.1
  max_depth: 6
  n_estimators: 100
  subsample: 0.8
  colsample_bytree: 0.8
  random_state: 42
train:
  n_folds: 5
  batch_size: 1000
  output_path: /app/output/cv_results.csv